############ Environment ############
env: "maze33"   # garnet / maze33 / cliffwalk
discount: 0.9

## maze33
maze33_success_prob: 0.9

############ Experiments ############

## Exp PE Exact
exp_pe_exact_num_iterations: 100
exp_pe_exact_alphas: [0, 0.1, 0.5, 0.8, 1]
exp_pe_exact_alphas_sensitivity: 0.02
exp_pe_exact_model_type: IdentitySmoothed # LocallySmoothed, IdentitySmoothed

## Exp Control Exact
exp_control_exact_num_iterations: 20
exp_control_exact_alphas: [0, 0.1, 0.5, 0.8, 1]
exp_control_exact_alphas_sensitivity: 0.02
exp_control_exact_model_type: IdentitySmoothed # LocallySmoothed, IdentitySmoothed
